/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatting.app;


import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Pritish
 */
public class HOSTPLAYER extends javax.swing.JFrame {

    /**
     * Creates new form chat_server
     */
    static ServerSocket ss;
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    static int flag = 0, x= 0,y=0;
    static int[][] a = new int[3][3];
     static int Over=0;
    public HOSTPLAYER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        b6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg_area.setBackground(new java.awt.Color(0, 0, 0));
        msg_area.setColumns(20);
        msg_area.setForeground(new java.awt.Color(250, 250, 250));
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        msg_send.setText("Ask other player to make a move");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 0, 0));
        jLabel1.setText("TIC TAC TOE");

        b7.setBackground(new java.awt.Color(255, 129, 0));
        b7.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b7.setText(" ");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(255, 129, 0));
        b8.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b8.setText(" ");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(255, 129, 0));
        b1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b1.setText(" ");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(255, 129, 0));
        b2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b2.setText(" ");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(255, 129, 0));
        b3.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b3.setText(" ");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(255, 129, 0));
        b9.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b9.setText(" ");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(255, 129, 0));
        b4.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b4.setText(" ");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 32, 247));
        jLabel2.setText("X");

        b5.setBackground(new java.awt.Color(255, 129, 0));
        b5.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b5.setText(" ");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 3, 0));
        jLabel3.setText("O");

        b6.setBackground(new java.awt.Color(255, 129, 0));
        b6.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        b6.setText(" ");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(156, 156, 156)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msg_send, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      public static boolean draw(){
        int count=0;
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){
                if(a[i][j] == ' '){
                    count++;
                }
            }
        }
        return count == 0;
    }
    
    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        // TODO add your handling code here:
        if(flag == 0){
            JOptionPane.showMessageDialog(null, "Please make your move");
            return;
        }
        switch (flag) {
                    case 1:
                        x = y = 0;
                        break;
                    case 2:
                        x = 0;
                        y = 1;
                        break;
                    case 3:
                        x = 0;
                        y = 2;
                        break;
                    case 4:
                        x = 1;
                        y = 0;
                        break;
                    case 5:
                        x = 1;
                        y = 1;
                        break;
                    case 6:
                        x = 1;
                        y = 2;
                        break;
                    case 7:
                        x = 2;
                        y = 0;
                        break;
                    case 8:
                        x = 2;
                        y = 1;
                        break;
                    case 9:
                        x = 2;
                        y = 2;
                        break;
                    default:
                        break;
                }
        String msgout = "Row = " + Integer.toString(x+1) + " Column = " + Integer.toString(y+1);
        try{
            if(checkAndMate() == true){
                    JOptionPane.showMessageDialog(null, "Game Over and You Win");
                    Over = 1;
                    msgout = "exit";
            }
            if(draw()){
                JOptionPane.showMessageDialog(null, "Game Over and Match Draw");
                Over = 1;
                msgout = "draw";
            }
            dout.writeUTF(msgout);
            msg_area.setText(msg_area.getText().trim()+"\nMe : "+msgout);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_msg_sendActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        String s = b7.getText();
        if(s == " " && flag == 0){
            a[2][0] = 'O';
            flag=7;
            b7.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        String s = b8.getText();
        if(s == " " && flag == 0){
            a[2][1] = 'O';
            flag=8;
            b8.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String s = b1.getText();
        if(s == " " && flag == 0){
            flag=1;
            a[0][0] = 'O';
            b1.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        String s = b2.getText();
        if(s == " " && flag == 0){
            a[0][1] = 'O';
            flag=2;
            b2.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        String s = b3.getText();
        if(s == " " && flag == 0){
            a[0][2] = 'O';
            flag=3;
            b3.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        String s = b9.getText();
        if(s == " " && flag == 0){
            a[2][2] = 'O';
            flag=9;
            b9.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        String s = b4.getText();
        if(s == " " && flag == 0){
            a[1][0] = 'O';
            flag=4;
            b4.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        String s = b5.getText();
        if(s == " " && flag == 0){
            a[1][1] = 'O';
            flag=5;
            b5.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        String s = b6.getText();
        if(s == " " && flag == 0){
            a[1][2] = 'O';
            flag=6;
            b6.setText("O");
        }else{
            JOptionPane.showMessageDialog(null, "Select the valid move");
        }
    }//GEN-LAST:event_b6ActionPerformed
    
    public static int generateFlag(int m, int n){
        if(m == 0 && n == 0){
            return 1;
        }if(m == 0 && n == 1){
            return 2;
        }if(m == 0 && n == 2){
            return 3;
        }if(m == 1 && n == 0){
            return 4;
        }if(m == 1 && n == 1){
            return 5;
        }if(m == 1 && n == 2){
            return 6;
        }if(m == 2 && n == 0){
            return 7;
        }if(m == 2 && n == 1){
            return 8;
        }if(m == 2 && n == 2){
            return 9;
        }
        return 0;
    }
      public static boolean checkAndMate(){
        
        for(int i=0;i<3;i++){
            int count=0;
            for(int j=0;j<3;j++){
                if(a[i][j] == 'O'){
                    ++count;
                }
            }
            if(count == 3){
                return true;
            }
        }
        for(int j=0;j<3;j++){
            int count=0;
            for(int i=0;i<3;i++){
                if(a[i][j] == 'O'){
                    ++count;
                }
            }
            if(count == 3){
                return true;
            }
        }
        int count = 0;
        for(int i=0;i<3;i++){
            if(a[i][i] == 'O'){
                ++count;
            }
        }
        if(count == 3){
            return true;
        }
        return a[0][2] == 'O' && a[1][1] == 'O' && a[2][0] == 'O';
    }
    
    public static void setButton(int F){
        switch (F) {
                    case 1:
                        b1.setText("X");
                        break;
                    case 2:
                       b2.setText("X");
                        break;
                    case 3:
                       b3.setText("X");
                        break;
                    case 4:
                       b4.setText("X");
                        break;
                    case 5:
                        b5.setText("X");
                        break;
                    case 6:
                        b6.setText("X");
                        break;
                    case 7:
                        b7.setText("X");
                        break;
                    case 8:
                       b8.setText("X");
                        break;
                    case 9:
                        b9.setText("X");
                        break;
                    default:
                        break;
                }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOSTPLAYER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOSTPLAYER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOSTPLAYER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOSTPLAYER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOSTPLAYER().setVisible(true);
            }
        });
        
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){
                a[i][j] = ' ';
            }
        }
        String msgin="" ;
        try{
            ss = new ServerSocket(3000);
            s = ss.accept();
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());
            while(!msgin.equals("exit")){
                msgin = din.readUTF();
                if(msgin.equals("exit")){
                    JOptionPane.showMessageDialog(null, "Game Over and You Lose");
                    break;
                }
                if(msgin.equals("draw")){
                    JOptionPane.showMessageDialog(null, "Game Over And Match Draw");
                    break;
                }
                msg_area.setText(msg_area.getText().trim()+"\nOther : "+msgin);
                int X,Y;
                X = msgin.charAt(6) - '0';
                Y = msgin.charAt(17) - '0'; 
                --X;
                --Y;
                a[X][Y] = 'X';
                setButton(generateFlag(X,Y));
                flag = 0;
                if(Over==1){
                    break;
                }
            }
        }
        catch(Exception e){
            
        }
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton b1;
    private static javax.swing.JButton b2;
    private static javax.swing.JButton b3;
    private static javax.swing.JButton b4;
    private static javax.swing.JButton b5;
    private static javax.swing.JButton b6;
    private static javax.swing.JButton b7;
    private static javax.swing.JButton b8;
    private static javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_send;
    // End of variables declaration//GEN-END:variables
}
